### PR TITLE
DefaultQuery was removed in GeoTools 22.0

### PR DESCRIPTION
**Pull request by ahuarte47**
See:
https://github.com/geotools/geotools/commit/aea8b8a3ac0625ec17dc4dcb5fc289a2a9fc5785

### CODE REVIEW

**Comment by jericks** [comment]
Looks good!  Thank you!

**Comment by ahuarte47** [comment]
Hi @jericks, but You closed this PR was without merging, it was mistake?

**Comment by jericks** [comment]
Sorry!  I guess I don't have merge privileges.

**Comment by ahuarte47** [comment]
@jericks no problem, thanks for your intention!

**Comment by jericks** [comment]
Just couldn't merge from my phone.

**Comment by ahuarte47** [comment]
Thank you very much @jericks !

**Pull request merged**
